const http=require('http'),fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'));const port=Number(process.env.PORT||8080),MAX=1500000;
const send=(r,o)=>r.write(JSON.stringify(o)+'\n'),sleep=ms=>new Promise(x=>setTimeout(x,ms));
async function read(req){let b='';for await(const c of req){b+=c;if(b.length>MAX)throw Error('Pedido grande demais')}return JSON.parse(b||'{}')}
function webProject(p){const calc=/calcul|soma|conta/.test(p);if(calc)return{message:'Criei uma calculadora completa sem usar API paga.',mode:'web',files:{'index.html':'<main class="calc"><h1>Calculadora</h1><input id="a" type="number" placeholder="Primeiro número"><select id="op"><option>+</option><option>-</option><option>×</option><option>÷</option></select><input id="b" type="number" placeholder="Segundo número"><button id="go">Calcular</button><output id="out">Resultado: —</output></main>','styles.css':'body{font-family:system-ui;margin:0;min-height:100vh;display:grid;place-items:center;background:linear-gradient(135deg,#111827,#4338ca)}.calc{width:min(360px,86vw);display:grid;gap:12px;background:white;padding:26px;border-radius:22px;box-shadow:0 22px 70px #0005}input,select,button,output{font:inherit;padding:12px;border-radius:10px;border:1px solid #d9dfeb}button{background:#315ee8;color:white;border:0;font-weight:700}output{background:#f2f5fb}','script.js':"go.onclick=()=>{let x=+a.value,y=+b.value,r;switch(op.value){case '+':r=x+y;break;case '-':r=x-y;break;case '×':r=x*y;break;case '÷':r=y?x/y:'Erro: divisão por zero'}out.value='Resultado: '+r}"}};
return{message:'Modo gratuito ativo. Montei um projeto web base; vou ampliar meu gerador local com mais tipos de pedido.',mode:'web',files:{'index.html':'<main><h1>Projeto criado</h1><p>AI Code Studio Zero: sem API, sem cobrança por tokens.</p><button id="b">Testar</button></main>','styles.css':'body{font-family:system-ui;padding:40px;background:#0b1020;color:#eef3ff}main{max-width:650px;margin:auto;background:#151d33;padding:30px;border-radius:20px}button{padding:12px 16px;border:0;border-radius:10px;background:#5f75ff;color:white}','script.js':"b.onclick=()=>console.log('Funcionando sem API paga')"}}}
function godotProject(){return{message:'Gerei um projeto Godot 4 3D sem API paga.',mode:'godot',files:{'project.godot':'[application]\nconfig/name="AI Code Studio 3D"\nrun/main_scene="res://main.tscn"\n[display]\nwindow/size/viewport_width=960\nwindow/size/viewport_height=540\n[rendering]\nrenderer/rendering_method="gl_compatibility"\n','main.tscn':'[gd_scene load_steps=2 format=3]\n\n[sub_resource type="BoxMesh" id="Box"]\nsize = Vector3(2,2,2)\n\n[node name="Main" type="Node3D"]\n[node name="Camera3D" type="Camera3D" parent="."]\nposition = Vector3(0,2.5,6)\ncurrent = true\n[node name="Cube" type="MeshInstance3D" parent="."]\nmesh = SubResource("Box")\n[node name="Light" type="DirectionalLight3D" parent="."]\nrotation_degrees = Vector3(-45,-30,0)\n'}}}
async function stream(r,x){for(const w of x.message.split(/(\s+)/)){send(r,{type:'chat',text:w});await sleep(12)}for(const [p,c] of Object.entries(x.files)){send(r,{type:'fileStart',path:p});for(let i=0;i<c.length;i+=100){send(r,{type:'file',text:c.slice(i,i+100)});await sleep(4)}send(r,{type:'fileEnd',path:p})}send(r,{type:'mode',mode:x.mode})}
async function agent(req,res){res.writeHead(200,{'content-type':'application/x-ndjson; charset=utf-8','cache-control':'no-cache'});try{const d=await read(req),p=String(d.prompt||'').toLowerCase();await stream(res,(/godot|3d/.test(p)?godotProject():webProject(p)))}catch(e){send(res,{type:'chat',text:'Erro: '+e.message})}res.end()}
http.createServer((req,res)=>{if(req.url==='/api/health'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});return res.end(JSON.stringify({ai:true,network:false,model:'AI Code Studio Zero (local)',version:'3-zero',cost:'R$ 0,00'}))}if(req.url==='/api/agent'&&req.method==='POST')return agent(req,res);if(req.url==='/'||req.url==='/index.html'){res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});return res.end(html)}res.writeHead(404);res.end('404')}).listen(port,'0.0.0.0',()=>console.log('AI Code Studio Zero on '+port));